### ISSUE TITLE
Status for channel binding implementation

### ISSUE THREAD

**Issue by LuciferSam86** [ongres/scram#8] opened 2020-10-19 14:23 UTC
Hi there,
is there any chance to see the channel binding implementation needed for  postgresql from version 11?

thanks!

**Comment by Neustradamus** [comment] 2020-11-12 04:49
@LuciferSam86, @ongres, @ahachete: It is supported no?
- https://github.com/ongres/scram/search?q=SCRAM-SHA-1-PLUS
- https://github.com/ongres/scram/search?q=SCRAM-SHA-256-PLUS

**Comment by Neustradamus** [comment] 2022-01-13 11:38
@LuciferSam86: Ping?

**Comment by davecramer** [comment] 2022-03-02 21:49
@ahachete Can you provide a status update here ?

**Comment by Neustradamus** [comment] 2023-11-19 01:56
Dear @ongres team, @ahachete,

I think that you have seen the jabber.ru MITM and Channel Binding is the solution:
- https://notes.valdikss.org.ru/jabber.ru-mitm/
- https://snikket.org/blog/on-the-jabber-ru-mitm/
- https://www.devever.net/~hl/xmpp-incident
- https://blog.jmp.chat/b/certwatch

Linked to:
- https://github.com/ongres/scram/issues/2
- https://github.com/ongres/scram/issues/8
- https://github.com/ongres/scram/issues/9
- https://github.com/ongres/scram/issues/19
- https://gitlab.com/ongresinc/scram/-/issues/15
- https://gitlab.com/ongresinc/scram/-/issues/17
- https://gitlab.com/ongresinc/scram/-/issues/18
- https://github.com/scram-sasl/info/issues/1

**Comment by jorsol** [comment] 2024-03-16 15:45
Closing as duplicate of #2

**Closed by jorsol** 2024-03-16 15:45 UTC
